### ISSUE TITLE
Pre-trained Model Missing

### ISSUE THREAD

**Issue by michellito** [danforthcenter/plantcv-tutorial_leaf_instance_segmentation#6]
Hello, I'm trying to go through this tutorial and it seems that the pre-trained model is no longer available at the link specified in the notebook:  https://datasci.danforthcenter.org/mask_rcnn_leaves_0060.h5.

Any help would be appreciated!

**Comment by nfahlgren** [comment]
Hi @michellito, I fixed the link on the webserver, it should be accessible now. Thanks!
